name: TabMan
main: org.CHIPTEC.tabman.TabMan
version: Alpha
commands:
   TabMan:
      aliases: [TM]
      description: Main Command.
      usage: /<command>
      permission: TM.Command
      permission-message: You don't have <permission> 
